# freq (in Hz) controller is called
controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 5.0 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 1.57 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 3.14
  acc_lim_x: 2.0
  acc_lim_y: 2.0

  # robot backup velocity in m/s
  escape_vel: -0.1

  sim_time: 1.0

  vx_samples: 5.0
  vtheta_samples: 10.0

  # goal_distance and path_distance are in meters (not cells)
  meter_scoring: true

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
